---
title: "EOO.habitat"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, echo=F, include = FALSE}
# library(ConR)
devtools::load_all()
```



## Example 1


Generate an artificial example dataset
```{r}

set.seed(3)
nbe_occ <- sample(seq(3, 100, 1), 500, replace = TRUE) ### 500 species with number of occurrences sampled between 3 and 100
ddlat <- lapply(nbe_occ, function(x) sample(seq(-10, 15, 0.1), x))
ddlon <- lapply(nbe_occ, function(x) sample(seq(7, 25, 0.1), x))
names(ddlon) <- names(ddlat) <- paste0("tax", seq(1,length(ddlat), 1))
ddlat <- lapply(seq_along(ddlat), function(i) data.frame(ddlat =  ddlat[[i]]))
ddlon <- lapply(seq_along(ddlon), function(i) data.frame(ddlon =  ddlon[[i]], taxa = names(ddlon)[i]))
test_data <- 
  data.frame(ddlat = do.call('rbind', ddlat), ddlon = do.call('rbind', ddlon)[,1], taxa = do.call('rbind', ddlon)[,2])
head(test_data)
dim(test_data)


```


```{r}

XY <- test_data[which(test_data$taxa == "tax1"),]
eoo <- EOO.comp(XY = XY)
spatial_eoo <- eoo$spatial.polygon

extract_elevation <- 
  elevatr::get_elev_raster(locations = as(spatial_eoo, "Spatial"), z = 4)

alt_filter <- extract_elevation > 500

alt_filter <- calc(extract_elevation, function(x) ifelse(x > 500, as.factor(1), as.factor(0)))

alt_filter <- ratify(alt_filter)
plot(alt_filter)
plot(spatial_eoo, add = T)

EOO.habitat(EOO.poly = spatial_eoo, hab.map = alt_filter)



land_cover <- raster::stack(paste0("D:/MonDossierR/conr_add_scripts/ESA_Land_Cover_map_1992_2015_AF_1km.tif"))

EOO.habitat(spatial_eoo, hab.map = land_cover, hab.class = 100, years = 20)


```



